### ISSUE TITLE
failed to generate the cert

### ISSUE THREAD

**Issue by citypw** [hardenedlinux/Debian-GNU-Linux-Profiles#2]
shawn@debian8-test:~/secureboot$ make
certtool -s --bits=2048 --outfile pk.key
Generating a self signed certificate...
You must specify --load-privkey
Makefile:12: recipe for target 'pk.key' failed
make: *** [pk.key] Error 1

@persmule could you plz fix it?

**Comment by persmule** [comment]
fixed in commit  6489bd8.
