### ISSUE TITLE
请问该项目和 公司： TYA infotech (广州市腾御安信息科技有限公司) 有关系吗？

### ISSUE THREAD

**Issue by atzlinux** [hardenedlinux/Debian-GNU-Linux-Profiles#49]
https://www.debian.org/consultants/#CN

发现在这里，有列出你们这个项目。

**Comment by citypw** [comment]
I put it there when I was working for TYA infotech but it's long time ago.

**Comment by atzlinux** [comment]
请问现在该公司和 hardenedlinux 项目，还有合作吗？


目前该公司在 Debian 网站的联系方式，全部无法联系，不确定这个公司是否还在提供 
Debian 顾问咨询服务。

如果还在提供 Debian 的顾问服务，就需要更新联系方式；

如果不再从事 Debian 的顾问服务，就需要从 Debian 网站上删除这个信息。

不知道能否帮忙确认下？


在 2022/6/30 17:38, Shawn C 写道:
>
> I put it there when I was working for TYA infotech but it's long time ago.
>

**Comment by citypw** [comment]
Not that I aware of. I think it stopped providing Debian consulting service for a while.
